cargo-features = ["panic-immediate-abort"]

[package]
name = "cb0"
version = "0.1.0"
edition = "2024"

[dependencies]
linux-syscall = "1.2.0"


[profile.release]
panic = "immediate-abort"
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
panic="abort"
